//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cpwide.rc
//
#define IDR_MAINFRAME                   2
#define IDR_PROLOGTYPE                  3
#define IDR_EDITTYPE                    3
#define IDR_PROGTYPE                    4
#define IDR_LISTENTYPE                  5
#define IDR_DEBUGTYPE                   6
#define IDR_LINKTYPE                    7
#define IDR_PROJTYPE                    8
#define IDR_BUILDTYPE                   9
#define IDR_COMPILETYPE                 10
#define IDD_ABOUTBOX                    100
#define IDR_WIDEAPP                     101
#define IDR_COGS                        102
#define IDD_DIALOG1                     103
#define IDD_ENTERNAME                   103
#define IDD_DEBUG                       104
#define IDD_SPYPOINTS                   105
#define IDP_PROJECT                     107
#define IDD_EXCEPT                      108
#define IDD_BROWSEBROWSER               109
#define IDD_UNLOCK                      110
#define IDB_TIBCO                       112
#define IDI_TIBCO                       113
#define IDC_PROPLM                      1000
#define IDC_TRACE                       1001
#define IDC_CREEP                       1002
#define IDC_ADDBUTTON                   1003
#define IDC_LEAP                        1003
#define IDC_DELBUTTON                   1004
#define IDC_SKIP                        1004
#define IDC_PROJLIST                    1005
#define IDC_FAIL                        1005
#define IDC_NEWPROJNAME                 1006
#define IDC_STOP                        1006
#define IDC_LEASH_CALL                  1008
#define IDC_LEASH_EXIT                  1009
#define IDC_LEASH_REDO                  1010
#define IDC_LEASH_FAIL                  1011
#define IDC_SPY                         1012
#define IDC_LEASH                       1013
#define IDC_SPY_SPYPOINTS               1015
#define IDC_SPYPOINTS                   1015
#define IDC_LOGFILE                     1015
#define IDC_LOGFILE2                    1016
#define IDC_DISPLAY                     1016
#define IDC_SPY_DELETE                  1017
#define IDC_SPY_CLEAR                   1018
#define IDC_NEWSPY                      1019
#define IDC_SPY_ADD                     1020
#define IDC_PREDICATES                  1021
#define IDC_FORMAT                      1023
#define IDC_FON                         1024
#define IDC_FOFF                        1025
#define IDC_BROWSE                      1026
#define IDP_CONSULT                     1027
#define IDP_BUILD                       1028
#define IDP_RUN                         1029
#define IDP_CLOSE                       1031
#define IDP_XPLFILE                     1032
#define IDP_DIRECTORY                   1033
#define IDP_FILELIST                    1034
#define IDP_LIBLIST                     1035
#define IDP_FILEADD                     1036
#define IDP_FILEDEL                     1037
#define IDP_LIBADD                      1038
#define IDP_LIBDEL                      1039
#define chx1                            0x0410
#define IDP_PROPLM                      1040
#define IDP_OPDEFS                      1041
#define IDC_E_READBUF                   1042
#define IDC_E_MESSAGE                   1044
#define IDC_ES_READBUF                  1045
#define IDC_ES_CALLSTACK                1046
#define IDC_E_CALLSTACK                 1047
#define IDC_BROWSEBROWSER               1048
#define IDC_USERNAME                    1049
#define IDC_SERIALNO                    1050
#define IDP_DIR_BROWSE                  1050
#define IDC_ORGANIZATION                1051
#define IDC_UNLOCKCODE                  1052
#define IDC_LOGGING                     1052
#define stc1                            0x0440
#define stc2                            0x0441
#define stc3                            0x0442
#define stc4                            0x0443
#define lst1                            0x0460
#define lst2                            0x0461
#define cmb1                            0x0470
#define cmb2                            0x0471
#define edt1                            0x0480
#define IDC_FILENAME                    0x0480
#define FILEOPENORD                     1536
#define IDD_PROJECT_EDIT                1536
#define ID_LISTENER_CONSULT             32771
#define ID_LISTEN_CONSULT               32772
#define ID_BUILD_PROJECTNEW             32773
#define ID_BUILD_PROJECTEDIT            32774
#define ID_LISTEN_RECONSULT             32775
#define ID_BUILD_RUNDOS                 32776
#define ID_VIEW_SETFONT                 32779
#define ID_VIEW_SETPRINTERFONT          32780
#define ID_BUILD_BUILD                  32781
#define ID_PROJECT_NEW                  32795
#define ID_MRU_PROJECT1                 32796
#define ID_MRU_PROJECT2                 32797
#define ID_MRU_PROJECT3                 32798
#define ID_MRU_PROJECT4                 32799
#define ID_MRU_PROJECT5                 32800
#define ID_MRU_PROJECT6                 32801
#define ID_MRU_PROJECT7                 32802
#define ID_MRU_PROJECT8                 32803
#define ID_MRU_PROJECT9                 32804
#define ID_MRU_PROJECT10                32805
#define ID_MRU_EDIT1                    32806
#define ID_MRU_EDIT2                    32807
#define ID_MRU_EDIT3                    32808
#define ID_MRU_EDIT4                    32809
#define ID_MRU_EDIT5                    32810
#define ID_MRU_EDIT6                    32811
#define ID_MRU_EDIT7                    32812
#define ID_MRU_EDIT8                    32813
#define ID_MRU_EDIT9                    32814
#define ID_MRU_EDIT10                   32815
#define ID_SAVE_ALL                     32816
#define ID_CLOSE_ALL                    32817
#define IDM_CHANGEBROWSER               32819
#define ID_FILE_UNLOCK                  32820
#define ID_HELP_LICENSE                 32821
#define ID_FILE_OPENPROJECT             32822
#define ID_HELP_PROLOG                  32823
#define ID_HELP_LOGICSERVER             32824
#define ID_HELP_TUTORIAL                32825
#define ID_HELP_NEWFEATURES             32826
#define ID_BUILDVERBOSE                 32827
#define ID_BUILD_VERBOSE                32828
#define ID_HELP_TIBICRULES              32829
#define ID_Menu                         32832
#define ID_HELP_WIDE                    32833
#define ID_FILE_PREVIEW                 40007
#define ID_FILE_PRINTSETUP              40009
#define ID_BUILD_COMPILE                40011
#define ID_BUILD_LINK                   40012
#define ID_BUILD_RUN                    40013
#define ID_LISTEN_START                 40014
#define ID_LISTEN_END                   40015
#define ID_LISTEN_OPENLOG               40016
#define ID_LISTEN_CLOSELOG              40017
#define ID_LISTEN_SAVE_AS               40018
#define ID_LISTEN_PRINT                 40019
#define ID_DEBUG_ON                     40020
#define ID_DEBUG_OFF                    40021
#define ID_DEBUG_SPY                    40022
#define ID_DEBUG_LEASHING               40023
#define IDS_LISTENER                    61216
#define IDS_COMPILER                    61217
#define IDS_LINKER                      61218
#define IDS_BUILDER                     61219

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
