C_FLAGS = -O6 -c -fpic

CC = gcc

all: xarray.lsx xarray.xpl

xarray.lsx: xarray.c
	$(CC) -I$(AMZI_DIR)/include $(C_FLAGS) -o xarray.o xarray.c
	$(CC) -shared -o xarray.lsx xarray.o

xarray.xpl: xarray.pro
	acmp xarray
	alnk xarray xarray
